[options]
admin_passwd = change_me
db_host = db
db_port = 5432
db_user = odoo
db_password = change_me

addons_path = /mnt/custom-addons,/mnt/extra-addons
data_dir = /var/lib/odoo

proxy_mode = False
list_db = True
dbfilter = ^.*$

logfile =
