[options]
admin_passwd = change_me
db_host = db
db_port = 5432
db_user = odoo
db_password = change_me

addons_path = /mnt/custom-addons,/mnt/custom-addons/muk_web_appsbar-19.0.1.1.6,/mnt/custom-addons/synconics_bi_dashboard-19.0.1.0.3
data_dir = /var/lib/odoo

proxy_mode = False
list_db = True
dbfilter =

logfile =
